package cc.moecraft.livelocation.database.model;

import cc.moecraft.livelocation.database.model.base.BaseDataLatest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataLatest extends BaseDataLatest<DataLatest> {
	
}
