package cc.moecraft.livelocation.database.model;

import cc.moecraft.livelocation.database.model.base.BaseDataLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataLog extends BaseDataLog<DataLog> {
	
}
