package cc.moecraft.livelocation.database.model;

import cc.moecraft.livelocation.database.model.base.BaseDataLog;

import static cc.moecraft.logger.utils.FormatUtils.resolve;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataLog extends BaseDataLog<DataLog>
{
    /**
     * Find latest data_log of a user
     *
     * @param username Username
     * @return Latest data log
     */
    public DataLog findLatest(String username)
    {
        return findFirst(resolve("SELECT * FROM data_log WHERE username=\"{}\" AND submit_time IN (SELECT DISTINCT MAX(submit_time) FROM data_log)", username));
    }
}
