package cc.moecraft.livelocation.database.model;

import cc.moecraft.livelocation.database.model.base.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo>
{
    /**
     * Update last active date to now.
     * Does not auto save.
     */
    public void updateLastActive()
    {
        setLastActive(System.currentTimeMillis());
    }
}
