package cc.moecraft.livelocation.database.model;

import cc.moecraft.livelocation.database.model.base.BaseUserInfo;
import cc.moecraft.livelocation.dataset.UserInfoDataset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo>
{
    /**
     * Update last active date to now.
     * Does not auto save.
     */
    public void updateLastActive()
    {
        setLastActive(System.currentTimeMillis());
    }

    /**
     * Update the data in database with the data in the dataset.
     *
     * @param dataset Dataset
     */
    public void updateFromDataset(UserInfoDataset dataset)
    {
        assert dataset.getUsername().equals(getUsername());
        updateLastActive();
        setAvatarUrl(dataset.getAvatarUrl());
        update();
    }
}
