package cc.moecraft.livelocation.database.model.base;

import io.jboot.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataLog<M extends BaseDataLog<M>> extends JbootModel<M> implements IBean {

	public void setIndex(java.lang.Long index) {
		set("index", index);
	}
	
	public java.lang.Long getIndex() {
		return getLong("index");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setSubmitTime(java.lang.Long submitTime) {
		set("submit_time", submitTime);
	}
	
	public java.lang.Long getSubmitTime() {
		return getLong("submit_time");
	}

	public void setSubmitIp(java.lang.String submitIp) {
		set("submit_ip", submitIp);
	}
	
	public java.lang.String getSubmitIp() {
		return getStr("submit_ip");
	}

	public void setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
	}
	
	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	public void setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
	}
	
	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

}
