package cc.moecraft.livelocation.database.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.JbootModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends JbootModel<M> implements IBean {

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setAvatarUrl(java.lang.String avatarUrl) {
		set("avatar_url", avatarUrl);
	}
	
	public java.lang.String getAvatarUrl() {
		return getStr("avatar_url");
	}

	public void setLastActive(java.lang.Long lastActive) {
		set("last_active", lastActive);
	}
	
	public java.lang.Long getLastActive() {
		return getLong("last_active");
	}

}
